server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usuarios
    username: root
    password: Admin123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Pragma Usuarios Plazoleta de comidas"
appVersion: "1.0.0"
